### ISSUE TITLE
如果详情页 是修改 添加页，应该怎么处理？

### ISSUE THREAD

**Issue by SanGongHappy** [Jin0811/KeepAlive#1]
如果详情页 是修改 添加页，我 现在还只能使用 activated 进行处理

**Comment by Jin0811** [comment]
你的意思应该是说，我们从列表页面进入到详情页面当中，然后进行编辑，保存数据，回到列表页面之后，因为组件是缓存的，所以无法看到最新的数据是吧？
当我们使用keep-alive组件缓存了组件之后，这个组件就会多出两个生命周期函数，分别为activated和deactivated，分别在组件激活和组件失活的时候被调用，可以在activated钩子当中进行数据的加载。
参考文档：https://v2.cn.vuejs.org/v2/api/#keep-alive
